import React, { type ReactNode } from "react";
import "./globals.css";
import { Providers } from "@/app/providers";

export const metadata = {
	title: "My App",
	description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
