import type { ReactNode } from "react";
import "./globals.css";
import { Providers } from "@/app/providers";
import { Box } from "@chakra-ui/react";

export const metadata = {
	title: "My App",
	description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<Box h="100vh">{children}</Box>
				</Providers>
			</body>
		</html>
	);
}
