import type { ReactNode } from "react";
import "./globals.css";
import { Providers } from "@/app/providers";
import Layout from "@/components/Layout";

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
