export const characters = [
  {
    id: "1",
    name: "Rick Sanchez",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: "1",
      name: "Earth (C-137)",
      type: "Planet",
      dimension: "Dimension C-137",
      residents: [],
    },
    location: {
      name: "Citadel of Ricks",
      id: "3",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
    episode: [],
  },
  {
    id: "2",
    name: "Morty Smith",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Citadel of Ricks",
      id: "3",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
    episode: [],
  },
  {
    id: "3",
    name: "Summer Smith",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Female",
    origin: {
      id: "20",
      name: "Earth (Replacement Dimension)",
      type: "Planet",
      dimension: "Replacement Dimension",
      residents: [],
    },
    location: {
      name: "Earth (Replacement Dimension)",
      id: "20",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
    episode: [],
  },
  {
    id: "4",
    name: "Beth Smith",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Female",
    origin: {
      id: "20",
      name: "Earth (Replacement Dimension)",
      type: "Planet",
      dimension: "Replacement Dimension",
      residents: [],
    },
    location: {
      name: "Earth (Replacement Dimension)",
      id: "20",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
    episode: [],
  },
  {
    id: "5",
    name: "Jerry Smith",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: "20",
      name: "Earth (Replacement Dimension)",
      type: "Planet",
      dimension: "Replacement Dimension",
      residents: [],
    },
    location: {
      name: "Earth (Replacement Dimension)",
      id: "20",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
    episode: [],
  },
  {
    id: "6",
    name: "Abadango Cluster Princess",
    status: "Alive",
    species: "Alien",
    type: "",
    gender: "Female",
    origin: {
      id: "2",
      name: "Abadango",
      type: "Cluster",
      dimension: "unknown",
      residents: [],
    },
    location: {
      name: "Abadango",
      id: "2",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/6.jpeg",
    episode: [],
  },
  {
    id: "7",
    name: "Abradolf Lincler",
    status: "unknown",
    species: "Human",
    type: "Genetic experiment",
    gender: "Male",
    origin: {
      id: "20",
      name: "Earth (Replacement Dimension)",
      type: "Planet",
      dimension: "Replacement Dimension",
      residents: [],
    },
    location: {
      name: "Testicle Monster Dimension",
      id: "21",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
    episode: [],
  },
  {
    id: "8",
    name: "Adjudicator Rick",
    status: "Dead",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Citadel of Ricks",
      id: "3",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
    episode: [],
  },
  {
    id: "9",
    name: "Agency Director",
    status: "Dead",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: "20",
      name: "Earth (Replacement Dimension)",
      type: "Planet",
      dimension: "Replacement Dimension",
      residents: [],
    },
    location: {
      name: "Earth (Replacement Dimension)",
      id: "20",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/9.jpeg",
    episode: [],
  },
  {
    id: "10",
    name: "Alan Rails",
    status: "Dead",
    species: "Human",
    type: "Superhuman (Ghost trains summoner)",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Worldender's lair",
      id: "4",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/10.jpeg",
    episode: [],
  },
  {
    id: "11",
    name: "Albert Einstein",
    status: "Dead",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: "1",
      name: "Earth (C-137)",
      type: "Planet",
      dimension: "Dimension C-137",
      residents: [],
    },
    location: {
      name: "Earth (Replacement Dimension)",
      id: "20",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/11.jpeg",
    episode: [],
  },
  {
    id: "12",
    name: "Alexander",
    status: "Dead",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: "1",
      name: "Earth (C-137)",
      type: "Planet",
      dimension: "Dimension C-137",
      residents: [],
    },
    location: {
      name: "Anatomy Park",
      id: "5",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/12.jpeg",
    episode: [],
  },
  {
    id: "13",
    name: "Alien Googah",
    status: "unknown",
    species: "Alien",
    type: "",
    gender: "unknown",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Earth (Replacement Dimension)",
      id: "20",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
    episode: [],
  },
  {
    id: "14",
    name: "Alien Morty",
    status: "unknown",
    species: "Alien",
    type: "",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Citadel of Ricks",
      id: "3",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/14.jpeg",
    episode: [],
  },
  {
    id: "15",
    name: "Alien Rick",
    status: "unknown",
    species: "Alien",
    type: "",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Citadel of Ricks",
      id: "3",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/15.jpeg",
    episode: [],
  },
  {
    id: "16",
    name: "Amish Cyborg",
    status: "Dead",
    species: "Alien",
    type: "Parasite",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Earth (Replacement Dimension)",
      id: "20",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/16.jpeg",
    episode: [],
  },
  {
    id: "17",
    name: "Annie",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Female",
    origin: {
      id: "1",
      name: "Earth (C-137)",
      type: "Planet",
      dimension: "Dimension C-137",
      residents: [],
    },
    location: {
      name: "Anatomy Park",
      id: "5",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/17.jpeg",
    episode: [],
  },
  {
    id: "18",
    name: "Antenna Morty",
    status: "Alive",
    species: "Human",
    type: "Human with antennae",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Citadel of Ricks",
      id: "3",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/18.jpeg",
    episode: [],
  },
  {
    id: "19",
    name: "Antenna Rick",
    status: "unknown",
    species: "Human",
    type: "Human with antennae",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "unknown",
      id: null,
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/19.jpeg",
    episode: [],
  },
  {
    id: "20",
    name: "Ants in my Eyes Johnson",
    status: "unknown",
    species: "Human",
    type: "Human with ants in his eyes",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Interdimensional Cable",
      id: "6",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/20.jpeg",
    episode: [],
  },
];
