export const characters = [
  {
    id: "1",
    name: "Rick Sanchez",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: "1",
      name: "Earth (C-137)",
      type: "Planet",
      dimension: "Dimension C-137",
      residents: [],
    },
    location: {
      name: "Citadel of Ricks",
      id: "3",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
    episode: [],
  },
  {
    id: "2",
    name: "Morty Smith",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Male",
    origin: {
      id: null,
      name: "unknown",
      type: null,
      dimension: null,
      residents: [],
    },
    location: {
      name: "Citadel of Ricks",
      id: "3",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
    episode: [],
  },
  {
    id: "3",
    name: "Summer Smith",
    status: "Alive",
    species: "Human",
    type: "",
    gender: "Female",
    origin: {
      id: "20",
      name: "Earth (Replacement Dimension)",
      type: "Planet",
      dimension: "Replacement Dimension",
      residents: [],
    },
    location: {
      name: "Earth (Replacement Dimension)",
      id: "20",
      residents: [],
    },
    image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
    episode: [],
  },
];
